spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/coupon_example
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 32
      connection-timeout: 5000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000